name = "image-background-remover"
compatibility_date = "2024-01-01"
main = ".next/server/middleware.js"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_APP_URL = "https://image-background-remover.pages.dev"
